[package]
name = "p2pss"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
clap = { version = "4.6.7", features = ["derive"] }
directories = "6.0.0"
eframe = "0.36.2"
gethostname = "1.1.0"
p2pss-capture = { version = "0.1.0", path = "../capture" }
p2pss-codec = { version = "0.1.0", path = "../codec" }
p2pss-discovery = { version = "0.1.0", path = "../discovery" }
p2pss-net = { version = "0.1.0", path = "../net" }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true
