[package]
name = "peeroxide-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.104"
cpal = "0.18.2"
rtrb = "0.4.0"
tracing = "0.1.44"

[lints]
workspace = true

[dev-dependencies]
clap = { version = "4.6.7", features = ["derive"] }

[target."cfg(windows)".dependencies]
wasapi = "0.24.0"
